version: "3"

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27217:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: DataSus123*

  grpc:
    image: sus:grpc
    build:
      context: ./
    container_name: sus_grpc
    restart: always
    ports:
      - 8081:80
    depends_on:
      - mongodb
